#!/bin/sh
set +xe
rm windows.*.zip
set -xe

cargo b
7z a windows.debug.zip $(pwd)/target/debug/sky-clash.exe $(pwd)/vendored-deps/msvc/runtime/* $(pwd)/textures

cargo b --release
7z a windows.release.zip $(pwd)/target/release/sky-clash.exe $(pwd)/vendored-deps/msvc/runtime/* $(pwd)/textures
