CREATE TABLE IF NOT EXISTS heroes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  rfid TEXT NOT NULL,
  level INTEGER NOT NULL,
  kind INTEGER NOT NULL,
  strength_points INTEGER NOT NULL,
  agility_points INTEGER NOT NULL,
  defence_points INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS matches (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  loser INTEGER NOT NULL,
  winner INTEGER NOT NULL,
  FOREIGN KEY(loser) REFERENCES heroes(id),
  FOREIGN KEY(winner) REFERENCES heroes(id)
);
